random_seed: 42
ckpt_path: null
gpus: "0,1"

# Dataset options:
data:
  root_path: "/project/shrikann_35/nmehlman/psid_data/vox1_feats"
  split: "train"
  max_sample_length: 512
  sr_embed_model: 'speechbrain'

# Dataloader options:
dataloader:
  train_batch_size: 64
  val_batch_size: 32
  num_workers: 8
  val_frac: 0.1

# Model options:
lightning:
  sr_fusion: true
  sr_embed_dim: 512
  sr_embeds_only: true
  hparams: 
    num_tokens: 28
    embedding_dim: 128
    d_model: 1024
    num_layers: 2
    dropout: 0.0
    local_attn_mask: 15
  optimizer_params:
    lr: 0.0005
  scheduler_params:
    T_max: 100
    eta_min: 0.00000


# Training options:
trainer:
  max_epochs: 100
  val_check_interval: 0.25 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  num_nodes: 1
  deterministic: False
  accumulate_grad_batches: 1

# Tensorboard options:
tensorboard:
  save_dir: "/home1/nmehlman/arts/vpc/logs/tensorboard/final/vox1/sr_only/"
  name: "wavlm"
  version: null     # Automatic versioning if set to null (recommended)


